
package pharmacie;

import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Moi
 */
public class Compagnie extends javax.swing.JFrame {

    public void Modifier() {
        comptab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table1MouseReleased(evt);
            }

            private void table1MouseReleased(MouseEvent evt) {
                int selectionner = comptab.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel) comptab.getModel();
                idc.setText(model.getValueAt(selectionner, 0).toString());
                nomc.setText(model.getValueAt(selectionner, 1).toString());
                adrs.setText(model.getValueAt(selectionner, 2).toString());
                tele.setText(model.getValueAt(selectionner, 3).toString());
                expr.setText(model.getValueAt(selectionner, 4).toString());

            }
        });

    }

    /**
     * Creates new form Compagnie
     */
    public Compagnie() {
        initComponents();
        SelectCompagnie();
        Modifier();
    }
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    public void SelectCompagnie() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacie", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("select * from compagnie");
            comptab.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        adrs = new javax.swing.JTextField();
        idc = new javax.swing.JTextField();
        mdf = new javax.swing.JButton();
        ajt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        comptab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        expr = new javax.swing.JTextField();
        nomc = new javax.swing.JTextField();
        tele = new javax.swing.JTextField();
        supp1 = new javax.swing.JButton();
        effacer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1516, 800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Gestion de la Compagnie");

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("ID");

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 51));
        jLabel9.setText("Nom");

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("Adresse");

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 51));
        jLabel12.setText("Téléphone");

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 51));
        jLabel13.setText("Expérience");

        adrs.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        adrs.setForeground(new java.awt.Color(0, 153, 51));

        idc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idc.setForeground(new java.awt.Color(0, 153, 51));

        mdf.setBackground(new java.awt.Color(0, 153, 51));
        mdf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mdf.setForeground(new java.awt.Color(255, 255, 255));
        mdf.setText("Modifier");
        mdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdfActionPerformed(evt);
            }
        });

        ajt.setBackground(new java.awt.Color(0, 153, 51));
        ajt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ajt.setForeground(new java.awt.Color(255, 255, 255));
        ajt.setText("Ajouter");
        ajt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajtActionPerformed(evt);
            }
        });

        comptab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comptab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom ", "Adresse", "Numèro de téléphone", "Expérience"
            }
        ));
        comptab.setRowHeight(30);
        comptab.setSelectionBackground(new java.awt.Color(0, 153, 51));
        jScrollPane1.setViewportView(comptab);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Liste des Compagnies");

        expr.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        expr.setForeground(new java.awt.Color(0, 153, 51));

        nomc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nomc.setForeground(new java.awt.Color(0, 153, 51));

        tele.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tele.setForeground(new java.awt.Color(0, 153, 51));

        supp1.setBackground(new java.awt.Color(0, 153, 51));
        supp1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        supp1.setForeground(new java.awt.Color(255, 255, 255));
        supp1.setText("Supprimer");
        supp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supp1MouseClicked(evt);
            }
        });
        supp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp1ActionPerformed(evt);
            }
        });

        effacer.setBackground(new java.awt.Color(0, 153, 51));
        effacer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        effacer.setForeground(new java.awt.Color(255, 255, 255));
        effacer.setText("Effacer");
        effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adrs, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(169, 169, 169))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addComponent(supp1)
                                .addGap(68, 68, 68)
                                .addComponent(effacer, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tele, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(ajt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mdf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nomc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(adrs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tele, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(expr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ajt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mdf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supp1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(effacer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ventes");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Médicaments");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Agents");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdfActionPerformed

        if (idc.getText().isEmpty() || nomc.getText().isEmpty() || adrs.getText().isEmpty() || tele.getText().isEmpty() || expr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tout les champs !", null, JOptionPane.ERROR_MESSAGE);
        } else {

            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacie", "root", "");
                String update = "update compagnie set nom='" + nomc.getText() + "'" + ",adresse='" + adrs.getText() + "'" + ",telephone='" + tele.getText() + "'" + ",experience='" + expr.getText() + "'" + "where id_c=" + idc.getText();
                Statement up = con.createStatement();
                up.executeUpdate(update);
                SelectCompagnie();
                idc.setText("");
                nomc.setText("");
                adrs.setText("");
                tele.setText("");
                expr.setText("");

                JOptionPane.showMessageDialog(null, "Une compagnie modifié avec succes!", null, JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erreur un compagnie n'est pas modifié!", null, JOptionPane.ERROR_MESSAGE);

            }
        }


    }//GEN-LAST:event_mdfActionPerformed

    private void ajtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajtActionPerformed
        // TODO add your handling code here:
        if (idc.getText().isEmpty() || tele.getText().isEmpty() || nomc.getText().isEmpty() || adrs.getText().isEmpty() || expr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tout les champs !", null, JOptionPane.ERROR_MESSAGE);

        } else {
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacie", "root", "");
                PreparedStatement add = con.prepareStatement("insert into compagnie values (?,?,?,?,?)");
                add.setString(1, (idc.getText()));
                add.setString(2, (nomc.getText()));
                add.setString(3, (adrs.getText()));
                add.setString(4, (tele.getText()));
                add.setString(5, (expr.getText()));

                int row = add.executeUpdate();
                con.close();
                SelectCompagnie();
                JOptionPane.showMessageDialog(null, "Compagnie ajouté avec succes !", null, JOptionPane.INFORMATION_MESSAGE);
                idc.setText("");
                nomc.setText("");
                adrs.setText("");
                tele.setText("");
                expr.setText("");

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "error d'ajout !", null, JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_ajtActionPerformed

    private void supp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp1ActionPerformed
        // TODO add your handling code here:
        if (idc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Le champs de l'ID est vide !", null, JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String nbr = idc.getText();
                con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacie", "root", "");
                String rq = "Select * from compagnie where id_c=?";
                PreparedStatement ps = con.prepareStatement(rq);
                ps.setString(1, nbr);
                rs = ps.executeQuery();
                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(null, "La Matricule n'existe pas !", null, JOptionPane.ERROR_MESSAGE);
                    idc.setText("");
                } else {

                    String dl = "Delete from compagnie where id_c=" + nbr;
                    Statement delt = con.createStatement();
                    delt.executeUpdate(dl);
                    SelectCompagnie();
                    JOptionPane.showMessageDialog(null, "une compagnie supprimé avec succes !", null, JOptionPane.INFORMATION_MESSAGE);
                    idc.setText("");
                     nomc.setText("");
                adrs.setText("");
                tele.setText("");
                expr.setText("");

                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_supp1ActionPerformed

    private void effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerActionPerformed
        idc.setText("");
                nomc.setText("");
                adrs.setText("");
                tele.setText("");
                expr.setText("");
    }//GEN-LAST:event_effacerActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
                  try{  
        new Medecine().setVisible(true);
        this.dispose();        
        }catch(Exception e){
            e.printStackTrace();
JOptionPane.showMessageDialog(null, "erreur !", null, JOptionPane.ERROR_MESSAGE);
               
        }  
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
                  try{  
        new Agents().setVisible(true);
        this.dispose();        
        }catch(Exception e){
            e.printStackTrace();
JOptionPane.showMessageDialog(null, "erreur !", null, JOptionPane.ERROR_MESSAGE);
               
        }  
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
                    try{  
        new vente().setVisible(true);
        this.dispose();        
        }catch(Exception e){
            e.printStackTrace();
JOptionPane.showMessageDialog(null, "erreur !", null, JOptionPane.ERROR_MESSAGE);
               
        } 
    }//GEN-LAST:event_jLabel2MouseClicked

    private void supp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_supp1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compagnie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compagnie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compagnie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compagnie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compagnie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adrs;
    private javax.swing.JButton ajt;
    private javax.swing.JTable comptab;
    private javax.swing.JButton effacer;
    private javax.swing.JTextField expr;
    private javax.swing.JTextField idc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mdf;
    private javax.swing.JTextField nomc;
    private javax.swing.JButton supp1;
    private javax.swing.JTextField tele;
    // End of variables declaration//GEN-END:variables
}
